spring:
  application:
    name: hello-java
management:
  endpoint:
    env:
      enabled: true
      show-values: always
      roles: ACTUATOR
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8085