# Default values for hello-java.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true

image:
  repository: acrjavahelena.azurecr.io/hello/hello-py
  tag: "latest"
  pullPolicy: Always

config:
  hello:
    message: "Hello from values yaml file - lets try syncing"
