name: Build Test and Push image on merge to main

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - build-and-push-workflow

jobs:
  build-test-and-push-main:
    runs-on: ubuntu-latest
    environment: aks

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run:  |
            ./gradlew clean build --no-daemon --stacktrace

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
          auth-type: service_principal

      - name: Login to Azure Container Registry
        run: |
          az acr login -n ${{ vars.AZURE_REGISTRY_URL }}

      - name: Set Git Hash env Variable
        run: |
          echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t ${{ vars.AZURE_REGISTRY_URL }}/hello-java:${{ env.SHORT_SHA }} .

      - name: Push Docker image to ACR - SHORT SHA
        run: |
          docker push ${{ vars.AZURE_REGISTRY_URL }}/hello-java:${{ env.SHORT_SHA }}  

      - name: Tag and Push Docker image to ACR - LATEST
        run: |
          docker tag ${{ vars.AZURE_REGISTRY_URL }}/hello-java:${{ env.SHORT_SHA }} ${{ vars.AZURE_REGISTRY_URL }}/hello-java:latest
          docker push ${{ vars.AZURE_REGISTRY_URL }}/hello-java:latest


