name: Deploy to AKS

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - deploy-to-aks

jobs:
  deploy-to-dev:
    runs-on: ubuntu-latest
    environment: aks

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Kubectl
      uses: azure/setup-kubectl@v4

    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
        auth-type: service_principal

    - name: Set AKS Context
      uses: azure/aks-set-context@v3
      with:
        resource-group: javahelenaResourceGroup
        cluster-name: javahelena-aks

    - name: Lint Helm Chart
      run: |
        cd k8s/hello-java
        helm lint

    - name: Deploy Helm Chart
      run: |
        cd k8s/hello-java
        helm upgrade --install --namespace hello hello-java . -f values.yaml